-- ============================================================================
-- BASELINE: estado actual del esquema en producción.
--
-- Reconstruido a partir del respaldo db_cluster-21-08-2026. Describe la base
-- tal como está HOY, incluyendo sus defectos. No corrige nada: las
-- correcciones van en las migraciones siguientes, para que quede registro de
-- qué cambió y por qué.
--
-- Solo esquema. Ningún dato de clientes vive en este archivo.
-- ============================================================================

-- ─── Tipos ──────────────────────────────────────────────────────────────────

CREATE TYPE public.payment_status AS ENUM ('completo', 'anticipo', 'faltante');
CREATE TYPE public.project_status AS ENUM ('cotizando', 'en_produccion', 'instalado');
CREATE TYPE public.user_role     AS ENUM ('cliente', 'vendedor', 'admin');

-- ─── Tablas ─────────────────────────────────────────────────────────────────

CREATE TABLE public.profiles (
    id          uuid NOT NULL PRIMARY KEY,
    first_name  text NOT NULL,
    middle_name text,
    last_name_p text NOT NULL,
    last_name_m text,
    email       text NOT NULL,
    phone       text,
    role        public.user_role DEFAULT 'cliente'::public.user_role,
    username    text,
    created_at  timestamp with time zone DEFAULT now()
);

CREATE TABLE public.products (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    description text,
    price       numeric(12,2) NOT NULL,
    image_url   text,
    is_active   boolean DEFAULT true,
    created_at  timestamp with time zone DEFAULT now(),
    stock       integer DEFAULT 0
);

CREATE TABLE public.orders (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id         uuid,
    seller_id         uuid,
    subtotal          numeric(12,2) NOT NULL,
    tax               numeric(12,2) NOT NULL,
    total             numeric(12,2) NOT NULL,
    payment_status    public.payment_status DEFAULT 'anticipo'::public.payment_status,
    project_status    public.project_status DEFAULT 'cotizando'::public.project_status,
    created_at        timestamp with time zone DEFAULT now(),
    notes             text,
    client_first_name text,
    client_last_name  text,
    client_phone      text,
    client_email      text
);

CREATE TABLE public.order_items (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     bigint REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id   bigint REFERENCES public.products(id),
    custom_label text,
    quantity     integer DEFAULT 1,
    unit_price   numeric(12,2) NOT NULL
);

CREATE TABLE public.custom_requests (
    id             uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    first_name     text,
    middle_name    text,
    last_name_p    text,
    last_name_m    text,
    email          text,
    phone          text,
    specifications text,
    status         text DEFAULT 'Pendiente de Revisión'::text,
    created_at     timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- ─── Triggers ───────────────────────────────────────────────────────────────

-- NOTA: esta versión lee el rol desde raw_user_meta_data, que el cliente
-- controla en signUp(). Es la escalada de privilegios que corrige 0002.
CREATE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
BEGIN
  INSERT INTO public.profiles (
    id, first_name, middle_name, last_name_p, last_name_m, email, phone, role
  ) VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'first_name', 'Sin Nombre'),
    new.raw_user_meta_data->>'middle_name',
    COALESCE(new.raw_user_meta_data->>'last_name_p', 'Sin Apellido'),
    new.raw_user_meta_data->>'last_name_m',
    new.email,
    new.raw_user_meta_data->>'phone',
    COALESCE(new.raw_user_meta_data->>'role', 'cliente')::public.user_role
  );
  RETURN new;
END;
$$;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE FUNCTION public.generate_employee_username() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  IF NEW.role IN ('vendedor', 'admin') THEN
    NEW.username := LOWER(NEW.first_name) || '.' || LOWER(NEW.last_name_p);
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER tr_generate_username
    BEFORE INSERT OR UPDATE ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.generate_employee_username();

-- ─── RLS ────────────────────────────────────────────────────────────────────

ALTER TABLE public.profiles        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_requests ENABLE ROW LEVEL SECURITY;

-- ADVERTENCIA: todas estas políticas leen el rol desde el JWT
-- (user_metadata), campo que cualquier usuario puede reescribir con
-- auth.updateUser(). No protegen nada. Se reemplazan en 0002.

CREATE POLICY "Lectura publica del catalogo" ON public.products
    FOR SELECT USING (true);

CREATE POLICY "Admins pueden insertar productos" ON public.products
    FOR INSERT WITH CHECK ((((auth.jwt() -> 'user_metadata') ->> 'role') = 'admin'));

CREATE POLICY "Admins pueden editar productos" ON public.products
    FOR UPDATE USING ((((auth.jwt() -> 'user_metadata') ->> 'role') = 'admin'));

CREATE POLICY "Admins gestionan ordenes" ON public.orders
    USING ((((auth.jwt() -> 'user_metadata') ->> 'role') = 'admin'));

CREATE POLICY "Clientes ven sus ordenes" ON public.orders
    FOR SELECT USING (auth.uid() = client_id);

CREATE POLICY "Admins gestionan detalles de orden" ON public.order_items
    USING ((((auth.jwt() -> 'user_metadata') ->> 'role') = 'admin'));

CREATE POLICY "Lectura permitida para staff" ON public.profiles
    FOR SELECT USING (
        (((auth.jwt() -> 'user_metadata') ->> 'role') = 'admin')
     OR (((auth.jwt() -> 'user_metadata') ->> 'role') = 'empleado')
    );

CREATE POLICY "Public insert requests" ON public.custom_requests
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Staff select requests" ON public.custom_requests
    FOR SELECT USING (
        (((auth.jwt() -> 'user_metadata') ->> 'role') = ANY (ARRAY['admin', 'empleado']))
    );

CREATE POLICY "Staff update requests" ON public.custom_requests
    FOR UPDATE USING (
        (((auth.jwt() -> 'user_metadata') ->> 'role') = ANY (ARRAY['admin', 'empleado']))
    );

-- ─── Storage ────────────────────────────────────────────────────────────────

-- El bucket real se llama 'productos'. El código subía a 'product-images',
-- que no existe: por eso fallaba la carga de fotos. Se corrigió en el
-- cliente (config.js), no en una migración: el nombre correcto siempre fue
-- este y lo que estaba mal era el código.
INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('productos', 'productos', true, 10485760)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Lectura publica de imagenes" ON storage.objects
    FOR SELECT USING (bucket_id = 'productos');

CREATE POLICY "Admins pueden subir imagenes" ON storage.objects
    FOR INSERT WITH CHECK (
        bucket_id = 'productos'
        AND (((auth.jwt() -> 'user_metadata') ->> 'role') = 'admin')
    );
